services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: unless-stopped
    working_dir: /usr/src/app
    environment:
      DATABASE_URL: mysql://root:root@db:3306/midnightcode
      DB_ROOT_PASSWORD: root
      DB_NAME: midnightcode
      PORT: 3000
      JWT_SECRET: 9fK$2vLmQ8#xT7zP@rW5!uY3cN6*eA1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - node_network

  db:
    image: mysql:8.0
    container_name: node_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: midnightcode
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - node_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      retries: 10
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: node_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - node_network

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - db1
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db1:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - node_network

  db1:
    image: postgres:15
    container_name: sonarqube_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - node_network

volumes:
  dbdata:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql_data:

networks:
  node_network:
    driver: bridge