version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      DATABASE_URL: mysql://root:root@db:3306/midnightcode
      DB_ROOT_PASSWORD: root
      DB_NAME: midnightcode
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - node_network

  db:
    image: mysql:8.0
    container_name: node_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: midnightcode
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - node_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: node_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - node_network

volumes:
  dbdata:

networks:
  node_network:
    driver: bridge